name: Build

on:
  push:
    branches: ["*", "!master", "!dev"]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} for OriumNetwork
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@oriumnetwork"
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHB_TOKEN }}
      - name: Compile Smart Contracts
        run: npm run compile
      - name: Integration Tests
        run: npm test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      - name: Test Coverage
        run: npm run coverage
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
